### ISSUE TITLE
Download link for biograph model is broken

### ISSUE THREAD

**Issue by YannLeGuen** [spiralgenetics/biograph#13]
Hi,

Could you provide a download link for the biograph model (https://archive.spiralgenetics.com/files/models/biograph_model-7.1.0.ml) the current one is broken? I am happy to upload this file on a reliable storage platform.

I could not locate this file in the docker container.

Thanks,
Yann

**Comment by ACEnglish** [comment]
The link has been moved to https://zenodo.org/record/8273311 I'll update the documentation to reflect this change.
